[package]
name = "hal"
version = "0.1.0"
authors = ["Jason Ramapuram <jason.ramapuram@viasat.com>"]

[dependencies]
rustc-serialize = "*"
rand = "*"
nalgebra = "*"
arrayfire = { path ="/Users/jramapuram/projects/arrayfire-rust" }

[lib]
name = "hal"
path = "src/lib.rs"

[[example]]
name = "perceptron"
path = "examples/perceptron.rs"
